feat: Allow logging of request body for debug and above
irvinlim/apple-health-ingester pull request #10
Opened 2022-11-14 17:52 UTC by irvinlim

Adds support to dump HTTP request body for `--log=5` and above. This may help with debugging in case of schema changes.

2022-11-14 18:02 UTC, irvinlim commented
@tedpearson Considering your interest in the project, I think it would be great to have you to review my PRs as well! 

But it seems like I can only add reviewers who are collaborators on the project (I'm not too familiar with GitHub, I mostly use GitLab at work...) How would you like if I added you as a collaborator for this project?

2022-11-14 20:15 UTC, tedpearson commented
@irvinlim I'd be happy to be a collaborator on the project. Your project is really one of my pet projects now as well 😄 

My previous job was also GitLab and I was owner of many repos. At my latest job we're using Github but I only have elevated permissions on my personal projects.

2022-11-16 03:09 UTC, tedpearson requested changes
One needed change, otherwise good.

2022-11-16 04:27 UTC, irvinlim commented on cmd/ingester/middlewares.go
> +				r.Body = io.NopCloser(bodyCopy)
Excellent catch! Updated.

2022-11-16 04:46 UTC, irvinlim commented on cmd/ingester/middlewares.go
> +			var buf bytes.Buffer
I think we can get around this problem by using `--http.authToken`, which avoids logging the request whatsoever if the request is unauthorized.

2022-11-16 04:47 UTC, tedpearson commented on cmd/ingester/middlewares.go
> +			var buf bytes.Buffer
True, works for me

2022-11-16 04:48 UTC, tedpearson approved these changes

2022-11-16 04:49 UTC, merged